# Generated by Django 3.1.1 on 2020-09-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200926_0841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'катгория', 'verbose_name_plural': 'категории'},
        ),
    ]
